### ISSUE TITLE
name it ForwardDiff

### ISSUE THREAD

**Issue by Beliavsky** [Nicholaswogan/ForwardDiff#2]
Minor thing, but ForwardDiff is more readable than forwarddiff, which is why the Julia project is called ForwardDiff.jl.

**Comment by Nicholaswogan** [comment]
I might just name the github repo ForwardDiff, but leave the library `libforwarddiff.a`. Does this seem reasonable? Or do you think the library should be named `libForwardDiff.a` as well

**Comment by Beliavsky** [comment]
Yes, it's fine for the library file to be all lower case. It's only for the name of the project that using camel case helps IMO.

**Comment by Nicholaswogan** [comment]
2f4cf296a98e152371db67ef4235b1c8cc5f1282
